// <auto-generated />
using HumanResourcesAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HumanResourcesAPI.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220921163656_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("HumanResourcesAPI.Data.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Birth")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Persons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Birth = "2000-12-12",
                            Category = "Category 1",
                            Description = "Hello World",
                            Name = "Karlo Bakota",
                            Rating = 4
                        },
                        new
                        {
                            Id = 2,
                            Birth = "2000-12-12",
                            Category = "Category 1",
                            Description = "Hello World",
                            Name = "Petar Mikulic",
                            Rating = 4
                        },
                        new
                        {
                            Id = 3,
                            Birth = "2000-12-12",
                            Category = "Category 2",
                            Description = "Hello World",
                            Name = "Tea Mikulic",
                            Rating = 4
                        },
                        new
                        {
                            Id = 4,
                            Birth = "2000-12-12",
                            Category = "Category 2",
                            Description = "Hello World",
                            Name = "Ivan Mikulic",
                            Rating = 4
                        },
                        new
                        {
                            Id = 5,
                            Birth = "2000-12-12",
                            Category = "Category 2",
                            Description = "Hello World",
                            Name = "Anamarija Mikulic",
                            Rating = 4
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
