// <auto-generated />
using HumanResourcesAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HumanResourcesAPI.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220922094205_Meetings")]
    partial class Meetings
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("HumanResourcesAPI.Data.Models.Meeting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Employed")
                        .HasColumnType("bit");

                    b.Property<string>("EmploymentDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InterviewDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("Meetings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Location 1",
                            Description = "Bad meeting",
                            Employed = false,
                            EmploymentDate = "NaN",
                            InterviewDate = "2022-12-12",
                            Name = "Meeting 1",
                            PersonId = 1,
                            Rating = 2
                        },
                        new
                        {
                            Id = 2,
                            Address = "Location 1",
                            Description = "Good meeting",
                            Employed = true,
                            EmploymentDate = "2022-12-20",
                            InterviewDate = "2022-12-15",
                            Name = "Meeting 2",
                            PersonId = 1,
                            Rating = 4
                        },
                        new
                        {
                            Id = 3,
                            Address = "Location 1",
                            Description = "Good meeting",
                            Employed = true,
                            EmploymentDate = "2022-12-13",
                            InterviewDate = "2022-12-12",
                            Name = "Meeting 1",
                            PersonId = 3,
                            Rating = 5
                        },
                        new
                        {
                            Id = 4,
                            Address = "Location 1",
                            Description = "Good meeting",
                            Employed = true,
                            EmploymentDate = "2022-12-13",
                            InterviewDate = "2022-12-12",
                            Name = "Meeting 1",
                            PersonId = 4,
                            Rating = 3
                        },
                        new
                        {
                            Id = 5,
                            Address = "Location 1",
                            Description = "Good meeting",
                            Employed = true,
                            EmploymentDate = "2022-12-13",
                            InterviewDate = "2022-12-12",
                            Name = "Meeting 1",
                            PersonId = 5,
                            Rating = 5
                        });
                });

            modelBuilder.Entity("HumanResourcesAPI.Data.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Birth")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Persons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Birth = "2000-12-12",
                            Category = "Category 1",
                            Description = "Hello World",
                            Name = "Karlo Bakota",
                            Rating = 4
                        },
                        new
                        {
                            Id = 2,
                            Birth = "2000-12-12",
                            Category = "Category 1",
                            Description = "Hello World",
                            Name = "Petar Mikulic",
                            Rating = 4
                        },
                        new
                        {
                            Id = 3,
                            Birth = "2000-12-12",
                            Category = "Category 2",
                            Description = "Hello World",
                            Name = "Tea Mikulic",
                            Rating = 4
                        },
                        new
                        {
                            Id = 4,
                            Birth = "2000-12-12",
                            Category = "Category 2",
                            Description = "Hello World",
                            Name = "Ivan Mikulic",
                            Rating = 4
                        },
                        new
                        {
                            Id = 5,
                            Birth = "2000-12-12",
                            Category = "Category 2",
                            Description = "Hello World",
                            Name = "Anamarija Mikulic",
                            Rating = 4
                        });
                });

            modelBuilder.Entity("HumanResourcesAPI.Data.Models.Meeting", b =>
                {
                    b.HasOne("HumanResourcesAPI.Data.Models.Person", "Person")
                        .WithMany("Meetings")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("HumanResourcesAPI.Data.Models.Person", b =>
                {
                    b.Navigation("Meetings");
                });
#pragma warning restore 612, 618
        }
    }
}
